p8105_hw2_sk5152
================
Shuting Kang
2022-09-29

## Problem 1 (not be graded)

\####1. read and clean the data (convert the entry variable from
character to logical variable)

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
    ## ✔ ggplot2 3.3.6      ✔ purrr   0.3.4 
    ## ✔ tibble  3.1.8      ✔ dplyr   1.0.10
    ## ✔ tidyr   1.2.0      ✔ stringr 1.4.1 
    ## ✔ readr   2.1.2      ✔ forcats 0.5.2 
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

``` r
getwd()
```

    ## [1] "/Users/shutingkang/Desktop/Columbia/P8105 DataScience/p8105_hw2_sk5152"

``` r
NYC_Subway=read_csv(file='./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv')
```

    ## Rows: 1868 Columns: 32
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
# clean up variable names after importing data
NYC_Subway=janitor::clean_names(NYC_Subway)
```

## Problem 2

#### Read and clean the Mr.Trash Wheel dataset

``` r
MrTrashWheel=
  readxl::read_excel("./data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx", sheet="Mr. Trash Wheel",range="A2:N534") %>%
  janitor::clean_names()%>%
  mutate(dumpster=as.numeric(dumpster))%>%
  filter(!is.na(dumpster))%>%
  mutate(sports_balls=round(sports_balls,0))%>%
  mutate(sports_balls=as.integer(sports_balls))
MrTrashWheel
```

    ## # A tibble: 453 × 14
    ##    dumpster month  year date                weight_tons volume…¹ plast…² polys…³
    ##       <dbl> <chr> <dbl> <dttm>                    <dbl>    <dbl>   <dbl>   <dbl>
    ##  1        1 May    2014 2014-05-16 00:00:00        4.31       18    1450    1820
    ##  2        2 May    2014 2014-05-16 00:00:00        2.74       13    1120    1030
    ##  3        3 May    2014 2014-05-16 00:00:00        3.45       15    2450    3100
    ##  4        4 May    2014 2014-05-17 00:00:00        3.1        15    2380    2730
    ##  5        5 May    2014 2014-05-17 00:00:00        4.06       18     980     870
    ##  6        6 May    2014 2014-05-20 00:00:00        2.71       13    1430    2140
    ##  7        7 May    2014 2014-05-21 00:00:00        1.91        8     910    1090
    ##  8        8 May    2014 2014-05-28 00:00:00        3.7        16    3580    4310
    ##  9        9 June   2014 2014-06-05 00:00:00        2.52       14    2400    2790
    ## 10       10 June   2014 2014-06-11 00:00:00        3.76       18    1340    1730
    ## # … with 443 more rows, 6 more variables: cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, grocery_bags <dbl>, chip_bags <dbl>,
    ## #   sports_balls <int>, homes_powered <dbl>, and abbreviated variable names
    ## #   ¹​volume_cubic_yards, ²​plastic_bottles, ³​polystyrene

#### import, clean, and organize the data for Professor Trash Wheel

``` r
ProfTrashWheel=
  readxl::read_excel("./data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx", sheet="Professor Trash Wheel",range="A2:N117") %>%
  janitor::clean_names()%>%
  mutate(dumpster=as.numeric(dumpster))%>%
  filter(!is.na(dumpster))%>%
  mutate(sports_balls=round(sports_balls,0))%>%
  mutate(sports_balls=as.integer(sports_balls))
ProfTrashWheel
```

    ## # A tibble: 71 × 14
    ##    dumpster month     year date                weight_…¹ volum…² plast…³ polys…⁴
    ##       <dbl> <chr>    <dbl> <dttm>                  <dbl>   <dbl>   <dbl>   <dbl>
    ##  1        1 January   2017 2017-01-02 00:00:00      1.79      15    1950    6080
    ##  2        2 January   2017 2017-01-30 00:00:00      1.58      15    9540   11230
    ##  3        3 February  2017 2017-02-26 00:00:00      2.32      18    8350    9210
    ##  4        4 February  2017 2017-02-26 00:00:00      3.72      15    8590    1030
    ##  5        5 February  2017 2017-02-28 00:00:00      1.45      15    7830    9950
    ##  6        6 March     2017 2017-03-30 00:00:00      1.71      15    8210   10340
    ##  7        7 April     2017 2017-04-01 00:00:00      1.82      15    9830   11020
    ##  8        8 April     2017 2017-04-20 00:00:00      2.37      15    9240    8760
    ##  9        9 May       2017 2017-05-10 00:00:00      2.64      15    9540    8810
    ## 10       10 May       2017 2017-05-26 00:00:00      2.78      15    8230    7800
    ## # … with 61 more rows, 6 more variables: cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, grocery_bags <dbl>, chip_bags <dbl>,
    ## #   sports_balls <int>, homes_powered <dbl>, and abbreviated variable names
    ## #   ¹​weight_tons, ²​volume_cubic_yards, ³​plastic_bottles, ⁴​polystyrene

#### combine Professor Trash Wheel with Mr. Trash Wheel

``` r
MTW=mutate(MrTrashWheel,resource='M')
PTW=mutate(ProfTrashWheel,resource='P')
TW=rbind(MTW,PTW)
TW
```

    ## # A tibble: 524 × 15
    ##    dumpster month  year date                weight_tons volume…¹ plast…² polys…³
    ##       <dbl> <chr> <dbl> <dttm>                    <dbl>    <dbl>   <dbl>   <dbl>
    ##  1        1 May    2014 2014-05-16 00:00:00        4.31       18    1450    1820
    ##  2        2 May    2014 2014-05-16 00:00:00        2.74       13    1120    1030
    ##  3        3 May    2014 2014-05-16 00:00:00        3.45       15    2450    3100
    ##  4        4 May    2014 2014-05-17 00:00:00        3.1        15    2380    2730
    ##  5        5 May    2014 2014-05-17 00:00:00        4.06       18     980     870
    ##  6        6 May    2014 2014-05-20 00:00:00        2.71       13    1430    2140
    ##  7        7 May    2014 2014-05-21 00:00:00        1.91        8     910    1090
    ##  8        8 May    2014 2014-05-28 00:00:00        3.7        16    3580    4310
    ##  9        9 June   2014 2014-06-05 00:00:00        2.52       14    2400    2790
    ## 10       10 June   2014 2014-06-11 00:00:00        3.76       18    1340    1730
    ## # … with 514 more rows, 7 more variables: cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, grocery_bags <dbl>, chip_bags <dbl>,
    ## #   sports_balls <int>, homes_powered <dbl>, resource <chr>, and abbreviated
    ## #   variable names ¹​volume_cubic_yards, ²​plastic_bottles, ³​polystyrene

#### dataset description

The combined DataSets contained 524 observations There were 15
variables, included dumpster,month, year, date,the weight of trash in
tons, the number of glass bottles, etc. During combination procedure,
additional character variable ‘resource’ was added to keep track of
which trash wheel is which. The total weight of trash collected by
Professor Trash Wheel was 135.5 tons; The total number of sports balls
collected by Mr.Trash Wheel was 856in 2020.

\##Problem 3

#### clean and data in pols-month

``` r
pols_month=
  read_csv("./data/pols-month.csv")%>%
  janitor::clean_names()%>%
  separate(mon,c("year","month","day"))%>%
  mutate(month=month.abb[as.numeric(month)])%>%
  mutate(president=ifelse(prez_gop==1,'gop','dem'))%>%
  select(-prez_dem,-prez_gop,-day)%>%
  mutate(year=as.integer(year))
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
pols_month
```

    ## # A tibble: 822 × 9
    ##     year month gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president
    ##    <int> <chr>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>    
    ##  1  1947 Jan        23      51     253      23      45     198 dem      
    ##  2  1947 Feb        23      51     253      23      45     198 dem      
    ##  3  1947 Mar        23      51     253      23      45     198 dem      
    ##  4  1947 Apr        23      51     253      23      45     198 dem      
    ##  5  1947 May        23      51     253      23      45     198 dem      
    ##  6  1947 Jun        23      51     253      23      45     198 dem      
    ##  7  1947 Jul        23      51     253      23      45     198 dem      
    ##  8  1947 Aug        23      51     253      23      45     198 dem      
    ##  9  1947 Sep        23      51     253      23      45     198 dem      
    ## 10  1947 Oct        23      51     253      23      45     198 dem      
    ## # … with 812 more rows

#### clean the data in snp.csv

``` r
snp=
  read_csv("./data/snp.csv")%>%
  janitor::clean_names()%>%
  separate(date,c("month","day","year"))%>%
  mutate(month=month.abb[as.numeric(month)],
         year=as.integer(year),
         year=as.integer(year))%>%
  mutate(year=case_when(year<22 ~year+2000,
                        year>22 ~year+1900))%>%
  select(-day, year,month,everything())
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
snp
```

    ## # A tibble: 787 × 4
    ##    month  year close day  
    ##    <chr> <dbl> <dbl> <chr>
    ##  1 Jul    2015 2080. 1    
    ##  2 Jun    2015 2063. 1    
    ##  3 May    2015 2107. 1    
    ##  4 Apr    2015 2086. 1    
    ##  5 Mar    2015 2068. 2    
    ##  6 Feb    2015 2104. 2    
    ##  7 Jan    2015 1995. 2    
    ##  8 Dec    2014 2059. 1    
    ##  9 Nov    2014 2068. 3    
    ## 10 Oct    2014 2018. 1    
    ## # … with 777 more rows

#### tidy the unemployment data so that it can be merged with the previous datasets

``` r
unemployment=
  read_csv("./data/unemployment.csv")%>%
  janitor::clean_names()%>%
  pivot_longer(jan:dec,names_to = "month",values_to = "unemployment")%>%
  mutate(month=str_to_title(month),year=as.integer(year))
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
unemployment
```

    ## # A tibble: 816 × 3
    ##     year month unemployment
    ##    <int> <chr>        <dbl>
    ##  1  1948 Jan            3.4
    ##  2  1948 Feb            3.8
    ##  3  1948 Mar            4  
    ##  4  1948 Apr            3.9
    ##  5  1948 May            3.5
    ##  6  1948 Jun            3.6
    ##  7  1948 Jul            3.6
    ##  8  1948 Aug            3.9
    ##  9  1948 Sep            3.8
    ## 10  1948 Oct            3.7
    ## # … with 806 more rows

#### join the datasets by merging snp into pols, and merging unemployment into the result

``` r
snp_to_pols=left_join(pols_month,snp,by=c("year","month"))
snp_to_pols
```

    ## # A tibble: 822 × 11
    ##     year month gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president close
    ##    <dbl> <chr>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>     <dbl>
    ##  1  1947 Jan        23      51     253      23      45     198 dem          NA
    ##  2  1947 Feb        23      51     253      23      45     198 dem          NA
    ##  3  1947 Mar        23      51     253      23      45     198 dem          NA
    ##  4  1947 Apr        23      51     253      23      45     198 dem          NA
    ##  5  1947 May        23      51     253      23      45     198 dem          NA
    ##  6  1947 Jun        23      51     253      23      45     198 dem          NA
    ##  7  1947 Jul        23      51     253      23      45     198 dem          NA
    ##  8  1947 Aug        23      51     253      23      45     198 dem          NA
    ##  9  1947 Sep        23      51     253      23      45     198 dem          NA
    ## 10  1947 Oct        23      51     253      23      45     198 dem          NA
    ## # … with 812 more rows, and 1 more variable: day <chr>

``` r
SPU=left_join(snp_to_pols,unemployment,by=c("year","month"))
SPU
```

    ## # A tibble: 822 × 12
    ##     year month gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president close
    ##    <dbl> <chr>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>     <dbl>
    ##  1  1947 Jan        23      51     253      23      45     198 dem          NA
    ##  2  1947 Feb        23      51     253      23      45     198 dem          NA
    ##  3  1947 Mar        23      51     253      23      45     198 dem          NA
    ##  4  1947 Apr        23      51     253      23      45     198 dem          NA
    ##  5  1947 May        23      51     253      23      45     198 dem          NA
    ##  6  1947 Jun        23      51     253      23      45     198 dem          NA
    ##  7  1947 Jul        23      51     253      23      45     198 dem          NA
    ##  8  1947 Aug        23      51     253      23      45     198 dem          NA
    ##  9  1947 Sep        23      51     253      23      45     198 dem          NA
    ## 10  1947 Oct        23      51     253      23      45     198 dem          NA
    ## # … with 812 more rows, and 2 more variables: day <chr>, unemployment <dbl>

#### write a short paragraph about these datasets, describe the result of the dataset

##### e.g. give the dimension, range of years, and names of key variables

the file “SPU” (pols-month+snp+unemployment datasets) contains 822
observations of 12 variables related to the number of national
politicians who are democratic or republican at any given time,
Standard&Poor’s stock market index at given time, and percentage of
unemployment at given time. The time composed by year and month.

The key variables include the year and month of the observation and
count, the number of republican/democratic governors on the associated
date, the number of republican/democratic senators on the associated
date, indicator of whether the president was repulican/democratic on the
associated date,the closing values of the S&P stock index on the
associated date, and percentage of unemployment in each month of the
associated year.

The range of years for file “SPU” across from 1947 to 2015 However,the
record for snp and unemployment at some given time were missing.
